trigger:
  branches:
    include:
      - none

variables:
  - group: WebAppDeploymentVariables

stages:
  - template: template.yml
    parameters:
      buildConfiguration: $(BuildConfiguration)
      azureSubscription: $(AzureSubscription)
      azureWebAppName: $(AzureWebAppName)
      resourceGroupName: $(ResourceGroupName)
